name: eyra-rank
channels:
  - defaults
dependencies:
  - pandas>=1.5
  - scikit-learn=2.1
  - joblib>=1.1
  - matplotlib>=3.7

 # channels:
#  - conda-forge

#dependencies:
#  - scikit-learn >= 1.2.1
#  - pandas >= 1
#  - matplotlib-base
#  - seaborn
#  - jupyterlab
#  - notebook
#  - plotly >= 5.10
#  - IPython
#  - packaging
